import {
  AppUser,
  Patient,
  Appointment,
  MedicationCatalogItem,
  MedicationOrder,
  ClinicalNote,
  FollowUpTask,
  SecureConversation,
  SecureMessage,
  AuditEvent,
  QueueTicket,
} from '../types/clinical';

export const INITIAL_USERS: AppUser[] = [
  {
    id: 'usr_nadia_martin',
    username: 'dr.martin',
    displayName: 'Dr. Nadia Martin',
    role: 'doctor',
    department: 'Médecine Générale & Urgences',
    licenseNumber: 'RPPS-10003492811',
    serviceCode: 'MED-GEN',
  },
  {
    id: 'usr_marc_lefevre',
    username: 'dr.lefevre',
    displayName: 'Dr. Marc Lefèvre',
    role: 'doctor',
    department: 'Cardiologie',
    licenseNumber: 'RPPS-10008821940',
    serviceCode: 'CARDIO',
  },
  {
    id: 'usr_sarah_benali',
    username: 'dr.benali',
    displayName: 'Dr. Sarah Benali',
    role: 'doctor',
    department: 'Pneumologie & Allergologie',
    licenseNumber: 'RPPS-10009148722',
    serviceCode: 'PNEUMO',
  },
  {
    id: 'usr_claire_morel',
    username: 'inf.morel',
    displayName: 'Claire Morel (IDE)',
    role: 'nurse',
    department: 'Soins & Consultations',
    serviceCode: 'SOINS',
  },
  {
    id: 'usr_karim_bensaid',
    username: 'acc.bensaid',
    displayName: 'Karim Bensaïd',
    role: 'receptionist',
    department: 'Accueil & Admission',
    serviceCode: 'ACCUEIL',
  },
  {
    id: 'usr_helene_auditor',
    username: 'dpo.auditor',
    displayName: 'Hélène Vasseur (DPO & Auditeur)',
    role: 'auditor',
    department: 'Conformité RGPD & HDS',
    serviceCode: 'AUDIT',
  },
  {
    id: 'usr_admin_sec',
    username: 'admin.sec',
    displayName: 'Alexandre Roux (Sécurité SI)',
    role: 'security_admin',
    department: 'Sécurité & Infrastructure',
    serviceCode: 'SEC-ADMIN',
  },
];

export const INITIAL_MEDICATIONS: MedicationCatalogItem[] = [
  {
    id: 'med_amox_1g',
    code: 'J01CA04',
    displayName: 'Amoxicilline 1000 mg',
    genericName: 'amoxicilline',
    category: 'Antibactérien bêta-lactamine',
    form: 'Comprimé dispersible',
    strength: '1 g',
    standardDose: '1 comprimé matin et soir',
    standardFrequency: '2 fois par jour',
    standardDurationDays: 6,
    routeOptions: ['Orale'],
    activeSubstances: ['amoxicilline'],
    allergenClasses: ['penicillin', 'beta_lactam', 'pénicilline'],
  },
  {
    id: 'med_augmentin_1g',
    code: 'J01CR02',
    displayName: 'Augmentin 1g/125mg (Amox/Ac. Clav)',
    genericName: 'amoxicilline / acide clavulanique',
    category: 'Antibactérien bêta-lactamine associé',
    form: 'Poudre pour suspension ou comprimé',
    strength: '1g / 125mg',
    standardDose: '1 sachet matin, midi et soir',
    standardFrequency: '3 fois par jour',
    standardDurationDays: 7,
    routeOptions: ['Orale'],
    activeSubstances: ['amoxicilline', 'acide_clavulanique'],
    allergenClasses: ['penicillin', 'beta_lactam', 'pénicilline'],
  },
  {
    id: 'med_ibuprofene_400',
    code: 'M01AE01',
    displayName: 'Ibuprofène 400 mg',
    genericName: 'ibuprofène',
    category: 'Anti-inflammatoire non stéroïdien (AINS)',
    form: 'Comprimé pelliculé',
    strength: '400 mg',
    standardDose: '1 comprimé au cours du repas',
    standardFrequency: '3 fois par jour si besoin',
    standardDurationDays: 5,
    routeOptions: ['Orale'],
    activeSubstances: ['ibuprofène'],
    allergenClasses: ['ains', 'anti_inflammatoire'],
  },
  {
    id: 'med_paracetamol_1g',
    code: 'N02BE01',
    displayName: 'Paracétamol 1000 mg',
    genericName: 'paracétamol',
    category: 'Antalgique / Antipyrétique',
    form: 'Gélule ou comprimé sécable',
    strength: '1000 mg',
    standardDose: '1 comprimé toutes les 6 heures (max 3g/j)',
    standardFrequency: '3 à 4 fois par jour si douleur',
    standardDurationDays: 5,
    routeOptions: ['Orale'],
    activeSubstances: ['paracétamol'],
    allergenClasses: ['paracétamol'],
  },
  {
    id: 'med_ramipril_5',
    code: 'C09AA05',
    displayName: 'Ramipril 5 mg',
    genericName: 'ramipril',
    category: 'Inhibiteur de l\'enzyme de conversion (IEC)',
    form: 'Comprimé sécable',
    strength: '5 mg',
    standardDose: '1 comprimé le matin',
    standardFrequency: '1 fois par jour',
    standardDurationDays: 30,
    routeOptions: ['Orale'],
    activeSubstances: ['ramipril'],
    allergenClasses: ['iec'],
  },
  {
    id: 'med_clarithro_500',
    code: 'J01FA09',
    displayName: 'Clarithromycine 500 mg',
    genericName: 'clarithromycine',
    category: 'Macrolide antibactérien',
    form: 'Comprimé enrobé',
    strength: '500 mg',
    standardDose: '1 comprimé matin et soir',
    standardFrequency: '2 fois par jour',
    standardDurationDays: 7,
    routeOptions: ['Orale'],
    activeSubstances: ['clarithromycine'],
    allergenClasses: ['macrolide'],
  },
  {
    id: 'med_metformine_1000',
    code: 'A10BA02',
    displayName: 'Metformine 1000 mg',
    genericName: 'metformine',
    category: 'Antidiabétique oral',
    form: 'Comprimé pelliculé',
    strength: '1000 mg',
    standardDose: '1 comprimé matin et soir à la fin du repas',
    standardFrequency: '2 fois par jour',
    standardDurationDays: 90,
    routeOptions: ['Orale'],
    activeSubstances: ['metformine'],
    allergenClasses: ['biguanide'],
  },
  {
    id: 'med_ventoline_100',
    code: 'R03AC02',
    displayName: 'Ventoline 100 µg/dose (Salbutamol)',
    genericName: 'salbutamol',
    category: 'Bronchodilatateur bêta-2 mimétique',
    form: 'Suspension pour inhalation',
    strength: '100 µg',
    standardDose: '1 à 2 bouffées en cas de crise d\'essoufflement',
    standardFrequency: 'Au besoin',
    standardDurationDays: 30,
    routeOptions: ['Inhalée'],
    activeSubstances: ['salbutamol'],
    allergenClasses: ['salbutamol'],
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat_aicha_diallo',
    medicalRecordNumber: 'MRN-2026-0814',
    familyName: 'Diallo',
    givenName: 'Aïcha',
    birthDate: '1984-05-14',
    gender: 'F',
    phone: '06 42 19 88 51',
    email: 'aicha.diallo@email.fr',
    address: {
      street: '14 rue des Lilas',
      city: 'Lyon',
      postalCode: '69003',
    },
    bloodGroup: 'A+',
    emergencyContact: {
      name: 'Moussa Diallo',
      relationship: 'Époux',
      phone: '06 42 19 88 52',
    },
    insurance: {
      provider: 'CPAM Rhône-Alpes + Mutuelle MGEN',
      policyNumber: 'MUT-94821034',
    },
    allergies: [
      {
        id: 'all_01',
        substanceCode: 'penicillin',
        substanceDisplay: 'Pénicilline & Bêta-lactamines',
        reaction: 'Angio-œdème de Quincke et urticaire aiguë après prise d\'amoxicilline (2021)',
        severity: 'critical',
        recordedAt: '2021-06-12T14:30:00Z',
        recordedBy: 'Dr. Martin',
        status: 'active',
      },
    ],
    problems: [
      {
        id: 'pr_01',
        codeSystem: 'CIM-10',
        code: 'I10',
        display: 'Hypertension artérielle essentielle',
        onsetDate: '2020-03-10',
        clinicalStatus: 'active',
      },
      {
        id: 'pr_02',
        codeSystem: 'CIM-10',
        code: 'J45.0',
        display: 'Asthme intermittent modéré',
        onsetDate: '2015-11-20',
        clinicalStatus: 'active',
      },
    ],
    vitalsHistory: [
      {
        id: 'vit_01_prev5',
        measuredAt: '2025-10-14T09:00:00Z',
        measuredBy: 'Dr. Marc Lefèvre',
        heightCm: 168,
        weightKg: 66.8,
        bmi: 23.7,
        systolic: 148,
        diastolic: 92,
        pulseBpm: 78,
        temperatureC: 36.7,
        respiratoryRate: 16,
        oxygenSaturation: 98,
      },
      {
        id: 'vit_01_prev4',
        measuredAt: '2025-12-08T14:30:00Z',
        measuredBy: 'Claire Morel (IDE)',
        heightCm: 168,
        weightKg: 66.2,
        bmi: 23.5,
        systolic: 144,
        diastolic: 88,
        pulseBpm: 74,
        temperatureC: 36.9,
        respiratoryRate: 15,
        oxygenSaturation: 98,
      },
      {
        id: 'vit_01_prev3',
        measuredAt: '2026-02-18T10:15:00Z',
        measuredBy: 'Dr. Nadia Martin',
        heightCm: 168,
        weightKg: 65.8,
        bmi: 23.3,
        systolic: 138,
        diastolic: 84,
        pulseBpm: 71,
        temperatureC: 37.0,
        respiratoryRate: 16,
        oxygenSaturation: 99,
      },
      {
        id: 'vit_01_prev2',
        measuredAt: '2026-04-20T15:45:00Z',
        measuredBy: 'Claire Morel (IDE)',
        heightCm: 168,
        weightKg: 65.4,
        bmi: 23.2,
        systolic: 134,
        diastolic: 82,
        pulseBpm: 70,
        temperatureC: 36.8,
        respiratoryRate: 15,
        oxygenSaturation: 99,
      },
      {
        id: 'vit_02',
        measuredAt: '2026-06-15T11:00:00Z',
        measuredBy: 'Dr. Nadia Martin',
        heightCm: 168,
        weightKg: 65.0,
        bmi: 23.0,
        systolic: 135,
        diastolic: 82,
        pulseBpm: 72,
        temperatureC: 36.8,
        respiratoryRate: 16,
        oxygenSaturation: 98,
      },
      {
        id: 'vit_01',
        measuredAt: '2026-09-28T09:15:00Z',
        measuredBy: 'Claire Morel (IDE)',
        heightCm: 168,
        weightKg: 64.5,
        bmi: 22.9,
        systolic: 128,
        diastolic: 78,
        pulseBpm: 68,
        temperatureC: 37.1,
        respiratoryRate: 15,
        oxygenSaturation: 99,
      },
    ],
    medicalHistory: ['Asthme infantile stabilisé', 'Migraines cataméniales'],
    surgicalHistory: ['Césarienne en 2017 sans complication'],
    riskFactors: ['Stress professionnel', 'Consommation caféine modérée'],
    status: 'active',
  },
  {
    id: 'pat_jc_bernard',
    medicalRecordNumber: 'MRN-2026-0422',
    familyName: 'Bernard',
    givenName: 'Jean-Claude',
    birthDate: '1958-03-29',
    gender: 'M',
    phone: '06 18 55 20 94',
    email: 'jc.bernard58@email.fr',
    address: {
      street: '28 avenue Berthelot',
      city: 'Lyon',
      postalCode: '69007',
    },
    bloodGroup: 'O+',
    emergencyContact: {
      name: 'Monique Bernard',
      relationship: 'Épouse',
      phone: '06 18 55 20 95',
    },
    insurance: {
      provider: 'CPAM (ALD Cardiopathie) + Harmonie Mutuelle',
      policyNumber: 'MUT-81729011',
    },
    allergies: [],
    problems: [
      {
        id: 'pr_03',
        codeSystem: 'CIM-10',
        code: 'I48.0',
        display: 'Fibrillation atriale paroxystique sous anticoagulant',
        onsetDate: '2022-09-01',
        clinicalStatus: 'active',
      },
      {
        id: 'pr_04',
        codeSystem: 'CIM-10',
        code: 'E78.0',
        display: 'Hypercholestérolémie pure',
        onsetDate: '2019-04-12',
        clinicalStatus: 'active',
      },
    ],
    vitalsHistory: [
      {
        id: 'vit_03_prev4',
        measuredAt: '2025-11-05T10:30:00Z',
        measuredBy: 'Dr. Marc Lefèvre',
        heightCm: 175,
        weightKg: 85.5,
        bmi: 27.9,
        systolic: 145,
        diastolic: 88,
        pulseBpm: 84,
        temperatureC: 36.8,
        respiratoryRate: 16,
        oxygenSaturation: 96,
      },
      {
        id: 'vit_03_prev3',
        measuredAt: '2026-01-19T09:45:00Z',
        measuredBy: 'Claire Morel (IDE)',
        heightCm: 175,
        weightKg: 84.6,
        bmi: 27.6,
        systolic: 140,
        diastolic: 85,
        pulseBpm: 76,
        temperatureC: 36.7,
        respiratoryRate: 15,
        oxygenSaturation: 97,
      },
      {
        id: 'vit_03_prev2',
        measuredAt: '2026-04-12T14:00:00Z',
        measuredBy: 'Dr. Marc Lefèvre',
        heightCm: 175,
        weightKg: 83.8,
        bmi: 27.4,
        systolic: 136,
        diastolic: 82,
        pulseBpm: 68,
        temperatureC: 36.9,
        respiratoryRate: 14,
        oxygenSaturation: 97,
      },
      {
        id: 'vit_03_prev1',
        measuredAt: '2026-07-08T11:20:00Z',
        measuredBy: 'Claire Morel (IDE)',
        heightCm: 175,
        weightKg: 82.9,
        bmi: 27.1,
        systolic: 134,
        diastolic: 82,
        pulseBpm: 66,
        temperatureC: 36.8,
        respiratoryRate: 14,
        oxygenSaturation: 98,
      },
      {
        id: 'vit_03',
        measuredAt: '2026-09-28T10:00:00Z',
        measuredBy: 'Claire Morel (IDE)',
        heightCm: 175,
        weightKg: 82.0,
        bmi: 26.8,
        systolic: 148,
        diastolic: 94,
        pulseBpm: 104,
        temperatureC: 36.9,
        respiratoryRate: 15,
        oxygenSaturation: 97,
      },
    ],
    medicalHistory: ['Fibrillation atriale', 'Syndrome coronarien aigu stenting 2021'],
    surgicalHistory: ['Angioplastie coronaire 2021', 'Appendicectomie 1974'],
    riskFactors: ['Tabagisme sevré il y a 8 ans', 'Surpoids modéré'],
    status: 'active',
  },
  {
    id: 'pat_chloe_moreno',
    medicalRecordNumber: 'MRN-2026-1109',
    familyName: 'Moreno',
    givenName: 'Chloé',
    birthDate: '1997-10-04',
    gender: 'F',
    phone: '07 88 12 34 56',
    email: 'chloe.moreno@email.fr',
    address: {
      street: '3 place Bellecour',
      city: 'Lyon',
      postalCode: '69002',
    },
    bloodGroup: 'B+',
    emergencyContact: {
      name: 'Lucie Moreno',
      relationship: 'Sœur',
      phone: '07 88 12 34 99',
    },
    insurance: {
      provider: 'CPAM Rhône + Alan',
      policyNumber: 'ALAN-449102',
    },
    allergies: [
      {
        id: 'all_02',
        substanceCode: 'sulfonamides',
        substanceDisplay: 'Sulfamides antibactériens',
        reaction: 'Éruption maculo-papuleuse étendue avec prurit intense',
        severity: 'moderate',
        recordedAt: '2023-01-18T10:00:00Z',
        recordedBy: 'Dr. Nadia Martin',
        status: 'active',
      },
    ],
    problems: [
      {
        id: 'pr_05',
        codeSystem: 'CIM-10',
        code: 'G43.0',
        display: 'Migraine sans aura récurrente',
        onsetDate: '2021-02-15',
        clinicalStatus: 'active',
      },
    ],
    vitalsHistory: [
      {
        id: 'vit_04_prev3',
        measuredAt: '2025-12-10T11:00:00Z',
        measuredBy: 'Dr. Nadia Martin',
        heightCm: 162,
        weightKg: 53.2,
        bmi: 20.3,
        systolic: 118,
        diastolic: 74,
        pulseBpm: 72,
        temperatureC: 36.8,
        respiratoryRate: 15,
        oxygenSaturation: 99,
      },
      {
        id: 'vit_04_prev2',
        measuredAt: '2026-03-14T15:30:00Z',
        measuredBy: 'Claire Morel (IDE)',
        heightCm: 162,
        weightKg: 52.8,
        bmi: 20.1,
        systolic: 115,
        diastolic: 72,
        pulseBpm: 68,
        temperatureC: 36.7,
        respiratoryRate: 14,
        oxygenSaturation: 99,
      },
      {
        id: 'vit_04_prev1',
        measuredAt: '2026-06-22T09:15:00Z',
        measuredBy: 'Dr. Nadia Martin',
        heightCm: 162,
        weightKg: 52.4,
        bmi: 20.0,
        systolic: 112,
        diastolic: 70,
        pulseBpm: 65,
        temperatureC: 36.6,
        respiratoryRate: 14,
        oxygenSaturation: 99,
      },
      {
        id: 'vit_04',
        measuredAt: '2026-09-27T16:00:00Z',
        measuredBy: 'Claire Morel (IDE)',
        heightCm: 162,
        weightKg: 52.0,
        bmi: 19.8,
        systolic: 114,
        diastolic: 72,
        pulseBpm: 66,
        temperatureC: 36.6,
        respiratoryRate: 14,
        oxygenSaturation: 99,
      },
    ],
    medicalHistory: ['Migraine chronique'],
    surgicalHistory: [],
    riskFactors: ['Travail sur écran prolongé'],
    status: 'active',
  },
  {
    id: 'pat_mamadou_traore',
    medicalRecordNumber: 'MRN-2026-0035',
    familyName: 'Traoré',
    givenName: 'Mamadou',
    birthDate: '1972-08-19',
    gender: 'M',
    phone: '06 99 41 83 20',
    email: 'm.traore@email.fr',
    address: {
      street: '7 avenue des Frères Lumière',
      city: 'Lyon',
      postalCode: '69008',
    },
    bloodGroup: 'AB+',
    emergencyContact: {
      name: 'Fatou Traoré',
      relationship: 'Épouse',
      phone: '06 99 41 83 21',
    },
    insurance: {
      provider: 'CPAM (ALD Diabète) + Malakoff Humanis',
      policyNumber: 'MUT-3382910',
    },
    allergies: [],
    problems: [
      {
        id: 'pr_06',
        codeSystem: 'CIM-10',
        code: 'E11.9',
        display: 'Diabète de type 2 sans complication rénale',
        onsetDate: '2018-05-12',
        clinicalStatus: 'active',
      },
    ],
    vitalsHistory: [
      {
        id: 'vit_05',
        measuredAt: '2026-09-25T14:00:00Z',
        measuredBy: 'Dr. Nadia Martin',
        heightCm: 180,
        weightKg: 89.0,
        bmi: 27.5,
        systolic: 144,
        diastolic: 92,
        pulseBpm: 76,
        temperatureC: 37.0,
        respiratoryRate: 16,
        oxygenSaturation: 98,
      },
    ],
    medicalHistory: ['Diabète de type 2 équilibré par Metformine'],
    surgicalHistory: ['Méniscectomie genou droit en 2005'],
    riskFactors: ['Sédentarité'],
    status: 'active',
  },
];

export const INITIAL_ACTIVE_ORDERS: MedicationOrder[] = [
  // Aïcha Diallo a déjà Ramipril
  {
    id: 'ord_01',
    patientId: 'pat_aicha_diallo',
    medicationId: 'med_ramipril_5',
    medicationDisplay: 'Ramipril 5 mg',
    genericName: 'ramipril',
    dosage: '1 comprimé par jour le matin',
    route: 'Orale',
    frequency: '1 fois / jour',
    durationDays: 30,
    quantity: '30 comprimés',
    refills: 2,
    patientInstructions: 'Prendre le matin au réveil avec un verre d\'eau.',
    clinicalIndication: 'Hypertension artérielle essentielle',
    prescriberId: 'usr_nadia_martin',
    prescriberName: 'Dr. Nadia Martin',
    authoredOn: '2026-09-01T10:00:00Z',
    status: 'active',
    signedAt: '2026-09-01T10:15:00Z',
    signedBy: 'usr_nadia_martin',
  },
  // Jean-Claude Bernard a déjà Warfarine et Atorvastatine
  {
    id: 'ord_02',
    patientId: 'pat_jc_bernard',
    medicationId: 'med_warfarin',
    medicationDisplay: 'Coumadine 5 mg (Warfarine)',
    genericName: 'warfarine',
    dosage: '1 comprimé le soir selon INR cible 2.0-3.0',
    route: 'Orale',
    frequency: '1 fois / jour le soir',
    durationDays: 90,
    quantity: '90 comprimés',
    refills: 1,
    patientInstructions: 'Surveiller les saignements et faire l\'INR mensuel.',
    clinicalIndication: 'Fibrillation atriale paroxystique',
    prescriberId: 'usr_marc_lefevre',
    prescriberName: 'Dr. Marc Lefèvre',
    authoredOn: '2026-08-20T11:00:00Z',
    status: 'active',
    signedAt: '2026-08-20T11:10:00Z',
    signedBy: 'usr_marc_lefevre',
  },
  {
    id: 'ord_03',
    patientId: 'pat_jc_bernard',
    medicationId: 'med_atorva',
    medicationDisplay: 'Tahor 20 mg (Atorvastatine)',
    genericName: 'atorvastatine',
    dosage: '1 comprimé le soir',
    route: 'Orale',
    frequency: '1 fois / jour le soir',
    durationDays: 90,
    quantity: '90 comprimés',
    refills: 2,
    patientInstructions: 'Signaler immédiatement toute douleur musculaire anormale.',
    clinicalIndication: 'Prévention secondaire cardiovasculaire',
    prescriberId: 'usr_marc_lefevre',
    prescriberName: 'Dr. Marc Lefèvre',
    authoredOn: '2026-08-20T11:00:00Z',
    status: 'active',
    signedAt: '2026-08-20T11:10:00Z',
    signedBy: 'usr_marc_lefevre',
  },
];

// Date de référence dynamique pour aujourd'hui (2026-09-29)
const todayStr = new Date().toISOString().split('T')[0];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt_01',
    patientId: 'pat_aicha_diallo',
    patientName: 'Aïcha Diallo',
    patientMrn: 'MRN-2026-0814',
    practitionerId: 'usr_nadia_martin',
    practitionerName: 'Dr. Nadia Martin',
    serviceCode: 'MED-GEN',
    appointmentType: 'consultation',
    startsAt: `${todayStr}T09:00:00.000Z`,
    endsAt: `${todayStr}T09:30:00.000Z`,
    status: 'completed',
    reason: 'Renouvellement traitement HTA et contrôle tensionnel',
    roomCode: 'Box 1',
    priority: 0,
  },
  {
    id: 'apt_02_conflict_target',
    patientId: 'pat_jc_bernard',
    patientName: 'Jean-Claude Bernard',
    patientMrn: 'MRN-2026-0422',
    practitionerId: 'usr_nadia_martin',
    practitionerName: 'Dr. Nadia Martin',
    serviceCode: 'MED-GEN',
    appointmentType: 'consultation',
    startsAt: `${todayStr}T10:30:00.000Z`,
    endsAt: `${todayStr}T11:00:00.000Z`,
    status: 'arrived', // En salle d'attente
    reason: 'Douleurs articulaires du genou et suivi biologique INR',
    roomCode: 'Box 1',
    priority: 1,
    queueTicketId: 'tkt_01',
  },
  {
    id: 'apt_03',
    patientId: 'pat_chloe_moreno',
    patientName: 'Chloé Moreno',
    patientMrn: 'MRN-2026-1109',
    practitionerId: 'usr_nadia_martin',
    practitionerName: 'Dr. Nadia Martin',
    serviceCode: 'MED-GEN',
    appointmentType: 'consultation',
    startsAt: `${todayStr}T11:30:00.000Z`,
    endsAt: `${todayStr}T12:00:00.000Z`,
    status: 'confirmed',
    reason: 'Crises migraineuses invalidantes depuis 10 jours',
    roomCode: 'Box 1',
    priority: 0,
  },
  {
    id: 'apt_04',
    patientId: 'pat_mamadou_traore',
    patientName: 'Mamadou Traoré',
    patientMrn: 'MRN-2026-0035',
    practitionerId: 'usr_marc_lefevre',
    practitionerName: 'Dr. Marc Lefèvre',
    serviceCode: 'CARDIO',
    appointmentType: 'suivi',
    startsAt: `${todayStr}T14:00:00.000Z`,
    endsAt: `${todayStr}T14:45:00.000Z`,
    status: 'booked',
    reason: 'Bilan cardiologique annuel et échocardiographie de contrôle',
    roomCode: 'Box 4',
    priority: 0,
  },
];

export const INITIAL_QUEUE_TICKETS: QueueTicket[] = [
  {
    id: 'tkt_01',
    appointmentId: 'apt_02_conflict_target',
    patientId: 'pat_jc_bernard',
    patientName: 'Jean-Claude Bernard',
    arrivedAt: `${todayStr}T10:18:00.000Z`,
    roomCode: 'Box 1',
    status: 'waiting',
    priority: 1,
  },
];

export const INITIAL_CLINICAL_NOTES: ClinicalNote[] = [
  {
    id: 'note_01',
    encounterId: 'enc_01',
    patientId: 'pat_aicha_diallo',
    subjective: {
      chiefComplaint: 'Renouvellement traitement HTA et céphalées intermittentes le matin',
      historyOfPresentIllness: 'La patiente signale une bonne tolérance du Ramipril 5mg, mais a ressenti quelques céphalées occipitales au réveil au cours de la dernière quinzaine.',
      symptoms: ['Céphalées matinales', 'Aucun vertige ni phosphène'],
    },
    objective: {
      physicalExam: 'Auscultation cardio-pulmonaire normale. B1 B2 réguliers sans souffle. Pas d\'œdème des membres inférieurs. Pression artérielle mesurée à 128/78 mmHg.',
      vitalsRecorded: INITIAL_PATIENTS[0].vitalsHistory[0],
    },
    assessment: {
      diagnoses: ['Hypertension artérielle essentielle bien équilibrée sous IEC'],
      clinicalEvaluation: 'Objectifs tensionnels atteints (< 130/80 mmHg). Absence de signe de retentissement aigu ou de décompensation.',
    },
    plan: {
      treatmentPlan: 'Poursuite Ramipril 5mg 1cp/j. Prescription d\'un bilan rénal de contrôle (créatininémie, DFG, ionogramme sanguin) à réaliser sous 1 mois.',
      patientAdvice: 'Maintenir la réduction des apports sodés et une activité physique modérée régulière.',
      dietaryRestrictions: 'Régime normosodé contrôlé.',
    },
    followUp: {
      recommendedDate: '2026-12-28',
      instructions: 'Revoir en consultation de suivi avec les résultats du bilan biologique dans 3 mois.',
    },
    noteVersion: 1,
    authoredBy: 'usr_nadia_martin',
    authoredByName: 'Dr. Nadia Martin',
    authoredAt: '2026-09-28T09:30:00Z',
    signedAt: '2026-09-28T09:32:00Z',
    signedBy: 'usr_nadia_martin',
    status: 'signed',
  },
];

export const INITIAL_FOLLOW_UPS: FollowUpTask[] = [
  {
    id: 'flw_01',
    patientId: 'pat_aicha_diallo',
    patientName: 'Aïcha Diallo',
    assignedToName: 'Dr. Nadia Martin',
    assignedToId: 'usr_nadia_martin',
    taskType: 'exam_control',
    title: 'Contrôle ionogramme & fonction rénale',
    objective: 'Vérifier la kaliémie et la créatininémie sous IEC Ramipril 5mg.',
    dueAt: '2026-10-15T00:00:00.000Z',
    priority: 'routine',
    status: 'pending',
  },
  {
    id: 'flw_02',
    patientId: 'pat_jc_bernard',
    patientName: 'Jean-Claude Bernard',
    assignedToName: 'Claire Morel (IDE)',
    assignedToId: 'usr_claire_morel',
    taskType: 'consultation_check',
    title: 'Vérification du résultat d\'INR mensuel',
    objective: 'S\'assurer de la stabilité de l\'INR entre 2.0 et 3.0 sous Coumadine.',
    dueAt: `${todayStr}T17:00:00.000Z`,
    priority: 'urgent',
    status: 'in_progress',
  },
  {
    id: 'flw_03',
    patientId: 'pat_mamadou_traore',
    patientName: 'Mamadou Traoré',
    assignedToName: 'Dr. Marc Lefèvre',
    assignedToId: 'usr_marc_lefevre',
    taskType: 'exam_control',
    title: 'Dosage HbA1c trimestriel',
    objective: 'Évaluer l\'équilibre glycémique sous Metformine (cible < 7.0%).',
    dueAt: '2026-09-20T00:00:00.000Z',
    priority: 'important',
    status: 'overdue',
  },
];

export const INITIAL_CONVERSATIONS: SecureConversation[] = [
  {
    id: 'conv_01',
    patientId: 'pat_aicha_diallo',
    patientName: 'Aïcha Diallo',
    practitionerId: 'usr_nadia_martin',
    practitionerName: 'Dr. Nadia Martin',
    subject: 'Question sur la posologie et le bilan sanguin',
    status: 'open',
    lastMessageAt: '2026-09-28T14:22:00Z',
    unreadByDoctor: true,
  },
  {
    id: 'conv_02',
    patientId: 'pat_chloe_moreno',
    patientName: 'Chloé Moreno',
    practitionerId: 'usr_nadia_martin',
    practitionerName: 'Dr. Nadia Martin',
    subject: 'Suivi de crise migraineuse et arrêt de travail',
    status: 'waiting_patient',
    lastMessageAt: '2026-09-27T17:45:00Z',
    unreadByDoctor: false,
  },
];

export const INITIAL_MESSAGES: Record<string, SecureMessage[]> = {
  conv_01: [
    {
      id: 'msg_01',
      conversationId: 'conv_01',
      senderType: 'patient',
      senderName: 'Aïcha Diallo',
      body: 'Bonjour Docteur, j\'ai récupéré mon ordonnance au laboratoire pour la prise de sang. Dois-je impérativement être à jeun pour le dosage de la créatinine ? Merci par avance.',
      sentAt: '2026-09-28T14:22:00Z',
      status: 'delivered',
      idempotencyKey: 'idemp_msg_001',
    },
  ],
  conv_02: [
    {
      id: 'msg_02',
      conversationId: 'conv_02',
      senderType: 'patient',
      senderName: 'Chloé Moreno',
      body: 'Docteur, le traitement prescrit soulage la crise en environ 45 minutes. Puis-je reprendre mon activité lundi si tout va bien ?',
      sentAt: '2026-09-27T16:10:00Z',
      status: 'read',
      idempotencyKey: 'idemp_msg_002',
    },
    {
      id: 'msg_03',
      conversationId: 'conv_02',
      senderType: 'doctor',
      senderName: 'Dr. Nadia Martin',
      body: 'Bonjour Chloé. Oui, vous pouvez reprendre dès lundi si les crises ne récidivent pas ce week-end. Pensez à bien vous hydrater et notez la fréquence sur votre carnet.',
      sentAt: '2026-09-27T17:45:00Z',
      status: 'delivered',
      idempotencyKey: 'idemp_msg_003',
    },
  ],
};

export const INITIAL_AUDIT_TRAIL: AuditEvent[] = [
  {
    id: 'aud_01',
    occurredAt: '2026-09-28T08:00:00Z',
    actorUserId: 'usr_nadia_martin',
    actorName: 'Dr. Nadia Martin',
    actorRole: 'doctor',
    action: 'USER_LOGIN',
    resourceType: 'session',
    outcome: 'allowed',
    reasonText: 'Authentification forte MFA réussie sur le poste de travail clinique',
    eventHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  },
  {
    id: 'aud_02',
    occurredAt: '2026-09-28T09:02:00Z',
    actorUserId: 'usr_nadia_martin',
    actorName: 'Dr. Nadia Martin',
    actorRole: 'doctor',
    action: 'PATIENT_RECORD_VIEW',
    resourceType: 'patient',
    resourceId: 'pat_aicha_diallo',
    patientId: 'pat_aicha_diallo',
    patientName: 'Aïcha Diallo',
    outcome: 'allowed',
    reasonText: 'Ouverture du dossier patient dans le cadre de la consultation programmée',
    eventHash: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
  },
  {
    id: 'aud_03',
    occurredAt: '2026-09-28T09:32:00Z',
    actorUserId: 'usr_nadia_martin',
    actorName: 'Dr. Nadia Martin',
    actorRole: 'doctor',
    action: 'CLINICAL_NOTE_SIGN',
    resourceType: 'clinical_note',
    resourceId: 'note_01',
    patientId: 'pat_aicha_diallo',
    patientName: 'Aïcha Diallo',
    outcome: 'allowed',
    reasonText: 'Signature électronique immuable de la consultation SOAP v1',
    eventHash: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
  },
  {
    id: 'aud_04',
    occurredAt: '2026-09-28T10:18:00Z',
    actorUserId: 'usr_karim_bensaid',
    actorName: 'Karim Bensaïd',
    actorRole: 'receptionist',
    action: 'QUEUE_TICKET_GENERATE',
    resourceType: 'queue_ticket',
    resourceId: 'tkt_01',
    patientId: 'pat_jc_bernard',
    patientName: 'Jean-Claude Bernard',
    outcome: 'allowed',
    reasonText: 'Enregistrement de l\'arrivée du patient en salle d\'attente',
    eventHash: 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d',
  },
];
